/* Experimental full microtiles: paired NEON loads and indexed FP32/FP64
 * FMAs. Called only at SVE VL128 for full 12x8 / 6x8 output blocks.
 * Each output accumulates K in order. No out-of-range prefetch or reads of C
 * in initializing mode; ordinary SVE code handles every tail and other VL.
 * All vector registers are declared clobbered, including ABI-saved halves. */
#ifndef CAMBLAS_PAIRED_MICRO8_H
#define CAMBLAS_PAIRED_MICRO8_H
#include <stddef.h>
#ifndef CAMBLAS_PAIRED_COLUMN_FIRST
#define CAMBLAS_PAIRED_COLUMN_FIRST 0
#endif
static __attribute__((always_inline)) inline void
camblas_paired_f32_block(int k, const float *a, size_t lda, const float *b, float *c, size_t ldc,
                         float alpha, int initialize)
{
    int depth = k, mode = (initialize ? 1 : 0) | (alpha == (float)1 ? 2 : 0);
    const float *ap = a, *bp = b;
    float *out = c;
    __asm__ volatile("movi v8.2d, #0\n\t"
                     "movi v9.2d, #0\n\t"
                     "movi v10.2d, #0\n\t"
                     "movi v11.2d, #0\n\t"
                     "movi v12.2d, #0\n\t"
                     "movi v13.2d, #0\n\t"
                     "movi v14.2d, #0\n\t"
                     "movi v15.2d, #0\n\t"
                     "movi v16.2d, #0\n\t"
                     "movi v17.2d, #0\n\t"
                     "movi v18.2d, #0\n\t"
                     "movi v19.2d, #0\n\t"
                     "movi v20.2d, #0\n\t"
                     "movi v21.2d, #0\n\t"
                     "movi v22.2d, #0\n\t"
                     "movi v23.2d, #0\n\t"
                     "movi v24.2d, #0\n\t"
                     "movi v25.2d, #0\n\t"
                     "movi v26.2d, #0\n\t"
                     "movi v27.2d, #0\n\t"
                     "movi v28.2d, #0\n\t"
                     "movi v29.2d, #0\n\t"
                     "movi v30.2d, #0\n\t"
                     "movi v31.2d, #0\n\t"
                     "cbz %w[depth], 2f\n\t"
                     ".p2align 5\n\t"
                     "1: ldp q4, q5, [%[a]]\n\t"
                     "ldr q6, [%[a], #32]\n\t"
                     "ldp q0, q1, [%[b]]\n\t"
#if CAMBLAS_PAIRED_COLUMN_FIRST
                     "fmla v8.4s, v4.4s, v0.s[0]\n\t"
                     "fmla v9.4s, v5.4s, v0.s[0]\n\t"
                     "fmla v10.4s, v6.4s, v0.s[0]\n\t"
                     "fmla v11.4s, v4.4s, v0.s[1]\n\t"
                     "fmla v12.4s, v5.4s, v0.s[1]\n\t"
                     "fmla v13.4s, v6.4s, v0.s[1]\n\t"
                     "fmla v14.4s, v4.4s, v0.s[2]\n\t"
                     "fmla v15.4s, v5.4s, v0.s[2]\n\t"
                     "fmla v16.4s, v6.4s, v0.s[2]\n\t"
                     "fmla v17.4s, v4.4s, v0.s[3]\n\t"
                     "fmla v18.4s, v5.4s, v0.s[3]\n\t"
                     "fmla v19.4s, v6.4s, v0.s[3]\n\t"
                     "fmla v20.4s, v4.4s, v1.s[0]\n\t"
                     "fmla v21.4s, v5.4s, v1.s[0]\n\t"
                     "fmla v22.4s, v6.4s, v1.s[0]\n\t"
                     "fmla v23.4s, v4.4s, v1.s[1]\n\t"
                     "fmla v24.4s, v5.4s, v1.s[1]\n\t"
                     "fmla v25.4s, v6.4s, v1.s[1]\n\t"
                     "fmla v26.4s, v4.4s, v1.s[2]\n\t"
                     "fmla v27.4s, v5.4s, v1.s[2]\n\t"
                     "fmla v28.4s, v6.4s, v1.s[2]\n\t"
                     "fmla v29.4s, v4.4s, v1.s[3]\n\t"
                     "fmla v30.4s, v5.4s, v1.s[3]\n\t"
                     "fmla v31.4s, v6.4s, v1.s[3]\n\t"
#else
                     "fmla v8.4s, v4.4s, v0.s[0]\n\t"
                     "fmla v11.4s, v4.4s, v0.s[1]\n\t"
                     "fmla v14.4s, v4.4s, v0.s[2]\n\t"
                     "fmla v17.4s, v4.4s, v0.s[3]\n\t"
                     "fmla v20.4s, v4.4s, v1.s[0]\n\t"
                     "fmla v23.4s, v4.4s, v1.s[1]\n\t"
                     "fmla v26.4s, v4.4s, v1.s[2]\n\t"
                     "fmla v29.4s, v4.4s, v1.s[3]\n\t"
                     "fmla v9.4s, v5.4s, v0.s[0]\n\t"
                     "fmla v12.4s, v5.4s, v0.s[1]\n\t"
                     "fmla v15.4s, v5.4s, v0.s[2]\n\t"
                     "fmla v18.4s, v5.4s, v0.s[3]\n\t"
                     "fmla v21.4s, v5.4s, v1.s[0]\n\t"
                     "fmla v24.4s, v5.4s, v1.s[1]\n\t"
                     "fmla v27.4s, v5.4s, v1.s[2]\n\t"
                     "fmla v30.4s, v5.4s, v1.s[3]\n\t"
                     "fmla v10.4s, v6.4s, v0.s[0]\n\t"
                     "fmla v13.4s, v6.4s, v0.s[1]\n\t"
                     "fmla v16.4s, v6.4s, v0.s[2]\n\t"
                     "fmla v19.4s, v6.4s, v0.s[3]\n\t"
                     "fmla v22.4s, v6.4s, v1.s[0]\n\t"
                     "fmla v25.4s, v6.4s, v1.s[1]\n\t"
                     "fmla v28.4s, v6.4s, v1.s[2]\n\t"
                     "fmla v31.4s, v6.4s, v1.s[3]\n\t"
#endif
                     "add %[a], %[a], %[as]\n\t"
                     "add %[b], %[b], #32\n\t"
                     "subs %w[depth], %w[depth], #1\n\t"
                     "b.ne 1b\n\t"
                     "2: tbnz %w[mode], #1, 11f\n\t"
                     "ld1r {v7.4s}, [%[alpha]]\n\t"
                     "fmul v8.4s, v8.4s, v7.4s\n\t"
                     "fmul v9.4s, v9.4s, v7.4s\n\t"
                     "fmul v10.4s, v10.4s, v7.4s\n\t"
                     "fmul v11.4s, v11.4s, v7.4s\n\t"
                     "fmul v12.4s, v12.4s, v7.4s\n\t"
                     "fmul v13.4s, v13.4s, v7.4s\n\t"
                     "fmul v14.4s, v14.4s, v7.4s\n\t"
                     "fmul v15.4s, v15.4s, v7.4s\n\t"
                     "fmul v16.4s, v16.4s, v7.4s\n\t"
                     "fmul v17.4s, v17.4s, v7.4s\n\t"
                     "fmul v18.4s, v18.4s, v7.4s\n\t"
                     "fmul v19.4s, v19.4s, v7.4s\n\t"
                     "fmul v20.4s, v20.4s, v7.4s\n\t"
                     "fmul v21.4s, v21.4s, v7.4s\n\t"
                     "fmul v22.4s, v22.4s, v7.4s\n\t"
                     "fmul v23.4s, v23.4s, v7.4s\n\t"
                     "fmul v24.4s, v24.4s, v7.4s\n\t"
                     "fmul v25.4s, v25.4s, v7.4s\n\t"
                     "fmul v26.4s, v26.4s, v7.4s\n\t"
                     "fmul v27.4s, v27.4s, v7.4s\n\t"
                     "fmul v28.4s, v28.4s, v7.4s\n\t"
                     "fmul v29.4s, v29.4s, v7.4s\n\t"
                     "fmul v30.4s, v30.4s, v7.4s\n\t"
                     "fmul v31.4s, v31.4s, v7.4s\n\t"
                     "11:\n\t"
                     "tbnz %w[mode], #0, 3f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v8.4s, v8.4s, v0.4s\n\t"
                     "fadd v9.4s, v9.4s, v1.4s\n\t"
                     "fadd v10.4s, v10.4s, v2.4s\n\t"
                     "3: stp q8, q9, [%[out]]\n\t"
                     "str q10, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 4f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v11.4s, v11.4s, v0.4s\n\t"
                     "fadd v12.4s, v12.4s, v1.4s\n\t"
                     "fadd v13.4s, v13.4s, v2.4s\n\t"
                     "4: stp q11, q12, [%[out]]\n\t"
                     "str q13, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 5f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v14.4s, v14.4s, v0.4s\n\t"
                     "fadd v15.4s, v15.4s, v1.4s\n\t"
                     "fadd v16.4s, v16.4s, v2.4s\n\t"
                     "5: stp q14, q15, [%[out]]\n\t"
                     "str q16, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 6f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v17.4s, v17.4s, v0.4s\n\t"
                     "fadd v18.4s, v18.4s, v1.4s\n\t"
                     "fadd v19.4s, v19.4s, v2.4s\n\t"
                     "6: stp q17, q18, [%[out]]\n\t"
                     "str q19, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 7f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v20.4s, v20.4s, v0.4s\n\t"
                     "fadd v21.4s, v21.4s, v1.4s\n\t"
                     "fadd v22.4s, v22.4s, v2.4s\n\t"
                     "7: stp q20, q21, [%[out]]\n\t"
                     "str q22, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 8f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v23.4s, v23.4s, v0.4s\n\t"
                     "fadd v24.4s, v24.4s, v1.4s\n\t"
                     "fadd v25.4s, v25.4s, v2.4s\n\t"
                     "8: stp q23, q24, [%[out]]\n\t"
                     "str q25, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 9f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v26.4s, v26.4s, v0.4s\n\t"
                     "fadd v27.4s, v27.4s, v1.4s\n\t"
                     "fadd v28.4s, v28.4s, v2.4s\n\t"
                     "9: stp q26, q27, [%[out]]\n\t"
                     "str q28, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 10f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v29.4s, v29.4s, v0.4s\n\t"
                     "fadd v30.4s, v30.4s, v1.4s\n\t"
                     "fadd v31.4s, v31.4s, v2.4s\n\t"
                     "10: stp q29, q30, [%[out]]\n\t"
                     "str q31, [%[out], #32]\n\t"
                     : [a] "+&r"(ap), [b] "+&r"(bp), [out] "+&r"(out), [depth] "+&r"(depth)
                     : [as] "r"(lda * sizeof(float)), [cs] "r"(ldc * sizeof(float)),
                       [alpha] "r"(&alpha), [mode] "r"(mode)
                     : "cc", "memory", "v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9",
                       "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20",
                       "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31");
}

static __attribute__((always_inline)) inline void
camblas_paired_f64_block(int k, const double *a, size_t lda, const double *b, double *c, size_t ldc,
                         double alpha, int initialize)
{
    int depth = k, mode = (initialize ? 1 : 0) | (alpha == (double)1 ? 2 : 0);
    const double *ap = a, *bp = b;
    double *out = c;
    __asm__ volatile("movi v8.2d, #0\n\t"
                     "movi v9.2d, #0\n\t"
                     "movi v10.2d, #0\n\t"
                     "movi v11.2d, #0\n\t"
                     "movi v12.2d, #0\n\t"
                     "movi v13.2d, #0\n\t"
                     "movi v14.2d, #0\n\t"
                     "movi v15.2d, #0\n\t"
                     "movi v16.2d, #0\n\t"
                     "movi v17.2d, #0\n\t"
                     "movi v18.2d, #0\n\t"
                     "movi v19.2d, #0\n\t"
                     "movi v20.2d, #0\n\t"
                     "movi v21.2d, #0\n\t"
                     "movi v22.2d, #0\n\t"
                     "movi v23.2d, #0\n\t"
                     "movi v24.2d, #0\n\t"
                     "movi v25.2d, #0\n\t"
                     "movi v26.2d, #0\n\t"
                     "movi v27.2d, #0\n\t"
                     "movi v28.2d, #0\n\t"
                     "movi v29.2d, #0\n\t"
                     "movi v30.2d, #0\n\t"
                     "movi v31.2d, #0\n\t"
                     "cbz %w[depth], 2f\n\t"
                     ".p2align 5\n\t"
                     "1: ldp q4, q5, [%[a]]\n\t"
                     "ldr q6, [%[a], #32]\n\t"
                     "ldp q0, q1, [%[b]]\n\t"
                     "ldp q2, q3, [%[b], #32]\n\t"
#if CAMBLAS_PAIRED_COLUMN_FIRST
                     "fmla v8.2d, v4.2d, v0.d[0]\n\t"
                     "fmla v9.2d, v5.2d, v0.d[0]\n\t"
                     "fmla v10.2d, v6.2d, v0.d[0]\n\t"
                     "fmla v11.2d, v4.2d, v0.d[1]\n\t"
                     "fmla v12.2d, v5.2d, v0.d[1]\n\t"
                     "fmla v13.2d, v6.2d, v0.d[1]\n\t"
                     "fmla v14.2d, v4.2d, v1.d[0]\n\t"
                     "fmla v15.2d, v5.2d, v1.d[0]\n\t"
                     "fmla v16.2d, v6.2d, v1.d[0]\n\t"
                     "fmla v17.2d, v4.2d, v1.d[1]\n\t"
                     "fmla v18.2d, v5.2d, v1.d[1]\n\t"
                     "fmla v19.2d, v6.2d, v1.d[1]\n\t"
                     "fmla v20.2d, v4.2d, v2.d[0]\n\t"
                     "fmla v21.2d, v5.2d, v2.d[0]\n\t"
                     "fmla v22.2d, v6.2d, v2.d[0]\n\t"
                     "fmla v23.2d, v4.2d, v2.d[1]\n\t"
                     "fmla v24.2d, v5.2d, v2.d[1]\n\t"
                     "fmla v25.2d, v6.2d, v2.d[1]\n\t"
                     "fmla v26.2d, v4.2d, v3.d[0]\n\t"
                     "fmla v27.2d, v5.2d, v3.d[0]\n\t"
                     "fmla v28.2d, v6.2d, v3.d[0]\n\t"
                     "fmla v29.2d, v4.2d, v3.d[1]\n\t"
                     "fmla v30.2d, v5.2d, v3.d[1]\n\t"
                     "fmla v31.2d, v6.2d, v3.d[1]\n\t"
#else
                     "fmla v8.2d, v4.2d, v0.d[0]\n\t"
                     "fmla v11.2d, v4.2d, v0.d[1]\n\t"
                     "fmla v14.2d, v4.2d, v1.d[0]\n\t"
                     "fmla v17.2d, v4.2d, v1.d[1]\n\t"
                     "fmla v20.2d, v4.2d, v2.d[0]\n\t"
                     "fmla v23.2d, v4.2d, v2.d[1]\n\t"
                     "fmla v26.2d, v4.2d, v3.d[0]\n\t"
                     "fmla v29.2d, v4.2d, v3.d[1]\n\t"
                     "fmla v9.2d, v5.2d, v0.d[0]\n\t"
                     "fmla v12.2d, v5.2d, v0.d[1]\n\t"
                     "fmla v15.2d, v5.2d, v1.d[0]\n\t"
                     "fmla v18.2d, v5.2d, v1.d[1]\n\t"
                     "fmla v21.2d, v5.2d, v2.d[0]\n\t"
                     "fmla v24.2d, v5.2d, v2.d[1]\n\t"
                     "fmla v27.2d, v5.2d, v3.d[0]\n\t"
                     "fmla v30.2d, v5.2d, v3.d[1]\n\t"
                     "fmla v10.2d, v6.2d, v0.d[0]\n\t"
                     "fmla v13.2d, v6.2d, v0.d[1]\n\t"
                     "fmla v16.2d, v6.2d, v1.d[0]\n\t"
                     "fmla v19.2d, v6.2d, v1.d[1]\n\t"
                     "fmla v22.2d, v6.2d, v2.d[0]\n\t"
                     "fmla v25.2d, v6.2d, v2.d[1]\n\t"
                     "fmla v28.2d, v6.2d, v3.d[0]\n\t"
                     "fmla v31.2d, v6.2d, v3.d[1]\n\t"
#endif
                     "add %[a], %[a], %[as]\n\t"
                     "add %[b], %[b], #64\n\t"
                     "subs %w[depth], %w[depth], #1\n\t"
                     "b.ne 1b\n\t"
                     "2: tbnz %w[mode], #1, 11f\n\t"
                     "ld1r {v7.2d}, [%[alpha]]\n\t"
                     "fmul v8.2d, v8.2d, v7.2d\n\t"
                     "fmul v9.2d, v9.2d, v7.2d\n\t"
                     "fmul v10.2d, v10.2d, v7.2d\n\t"
                     "fmul v11.2d, v11.2d, v7.2d\n\t"
                     "fmul v12.2d, v12.2d, v7.2d\n\t"
                     "fmul v13.2d, v13.2d, v7.2d\n\t"
                     "fmul v14.2d, v14.2d, v7.2d\n\t"
                     "fmul v15.2d, v15.2d, v7.2d\n\t"
                     "fmul v16.2d, v16.2d, v7.2d\n\t"
                     "fmul v17.2d, v17.2d, v7.2d\n\t"
                     "fmul v18.2d, v18.2d, v7.2d\n\t"
                     "fmul v19.2d, v19.2d, v7.2d\n\t"
                     "fmul v20.2d, v20.2d, v7.2d\n\t"
                     "fmul v21.2d, v21.2d, v7.2d\n\t"
                     "fmul v22.2d, v22.2d, v7.2d\n\t"
                     "fmul v23.2d, v23.2d, v7.2d\n\t"
                     "fmul v24.2d, v24.2d, v7.2d\n\t"
                     "fmul v25.2d, v25.2d, v7.2d\n\t"
                     "fmul v26.2d, v26.2d, v7.2d\n\t"
                     "fmul v27.2d, v27.2d, v7.2d\n\t"
                     "fmul v28.2d, v28.2d, v7.2d\n\t"
                     "fmul v29.2d, v29.2d, v7.2d\n\t"
                     "fmul v30.2d, v30.2d, v7.2d\n\t"
                     "fmul v31.2d, v31.2d, v7.2d\n\t"
                     "11:\n\t"
                     "tbnz %w[mode], #0, 3f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v8.2d, v8.2d, v0.2d\n\t"
                     "fadd v9.2d, v9.2d, v1.2d\n\t"
                     "fadd v10.2d, v10.2d, v2.2d\n\t"
                     "3: stp q8, q9, [%[out]]\n\t"
                     "str q10, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 4f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v11.2d, v11.2d, v0.2d\n\t"
                     "fadd v12.2d, v12.2d, v1.2d\n\t"
                     "fadd v13.2d, v13.2d, v2.2d\n\t"
                     "4: stp q11, q12, [%[out]]\n\t"
                     "str q13, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 5f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v14.2d, v14.2d, v0.2d\n\t"
                     "fadd v15.2d, v15.2d, v1.2d\n\t"
                     "fadd v16.2d, v16.2d, v2.2d\n\t"
                     "5: stp q14, q15, [%[out]]\n\t"
                     "str q16, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 6f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v17.2d, v17.2d, v0.2d\n\t"
                     "fadd v18.2d, v18.2d, v1.2d\n\t"
                     "fadd v19.2d, v19.2d, v2.2d\n\t"
                     "6: stp q17, q18, [%[out]]\n\t"
                     "str q19, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 7f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v20.2d, v20.2d, v0.2d\n\t"
                     "fadd v21.2d, v21.2d, v1.2d\n\t"
                     "fadd v22.2d, v22.2d, v2.2d\n\t"
                     "7: stp q20, q21, [%[out]]\n\t"
                     "str q22, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 8f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v23.2d, v23.2d, v0.2d\n\t"
                     "fadd v24.2d, v24.2d, v1.2d\n\t"
                     "fadd v25.2d, v25.2d, v2.2d\n\t"
                     "8: stp q23, q24, [%[out]]\n\t"
                     "str q25, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 9f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v26.2d, v26.2d, v0.2d\n\t"
                     "fadd v27.2d, v27.2d, v1.2d\n\t"
                     "fadd v28.2d, v28.2d, v2.2d\n\t"
                     "9: stp q26, q27, [%[out]]\n\t"
                     "str q28, [%[out], #32]\n\t"
                     "add %[out], %[out], %[cs]\n\t"
                     "tbnz %w[mode], #0, 10f\n\t"
                     "ldp q0, q1, [%[out]]\n\t"
                     "ldr q2, [%[out], #32]\n\t"
                     "fadd v29.2d, v29.2d, v0.2d\n\t"
                     "fadd v30.2d, v30.2d, v1.2d\n\t"
                     "fadd v31.2d, v31.2d, v2.2d\n\t"
                     "10: stp q29, q30, [%[out]]\n\t"
                     "str q31, [%[out], #32]\n\t"
                     : [a] "+&r"(ap), [b] "+&r"(bp), [out] "+&r"(out), [depth] "+&r"(depth)
                     : [as] "r"(lda * sizeof(double)), [cs] "r"(ldc * sizeof(double)),
                       [alpha] "r"(&alpha), [mode] "r"(mode)
                     : "cc", "memory", "v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9",
                       "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20",
                       "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31");
}

#endif
